### ISSUE TITLE
Clean Up CSS

### ISSUE THREAD

**Issue by una** [shower/shower#205]
Remove all inline CSS, create a structured system -- potentially in Sass

**Comment by pepelsbey** [comment]
There are two levels of styling available in all presentation systems (not just Shower, but even on desktop in Keynote, etc.)

1. Global theme
2. Local styling

The same applied to Shower. There’s a theme (based on elements like `<p>` or `<ul>` or special class names) and there’s per-slide styling (the one you call “inline styles”, I guess). It’s not possible to create ultimate theme for all cases in the world, that’s why you’ll always need inline styling. And since you’re usually work on exact slide, it’s much easier to style its content right in place, using `<style>`.

Speaking of structured system and Sass. There’s new version of Shower themes under development at the moment. They will be launched together with Shower 2.0 release coming soon. They have much better structure (split into modules), based on Sass (jus like existing ones) and introduce and few new features. See [next branch in shower/ribbon](https://github.com/shower/ribbon/tree/next) repo.

**Comment by una** [comment]
Its not very semantic this way. It can be avoided if there's a more lucid style system for people to edit. 

I'd  love to help with the Sass stuff if you want -- I've sort-of restructured Shower for my own use right now, and I'm using gulp and Browsersync in my build system so it runs automatically and minifies all the things.

**Comment by pepelsbey** [comment]
I don’t really see any problem with semantics here. Good old “inline styling is bad” rule could be applied only to situations when you duplicate styling on each page of your site. But presentation is a special case: there’s only one document which should be easily editable. That’s why there a theme that could be used in multiple presentations and there’s per-slide styling. I don’t see any other options to improve this system. But if there’s one — please go ahead, I’d like to know details.

**Comment by una** [comment]
Sure :) I'll take a stab at it and check out the Sass version thats in the works. I think its a really awesome project, just a little suggestion to make it even more awesome.
