### ISSUE TITLE
Bullet in <li> incorrectly rendered in Chrome/mac

### ISSUE THREAD

**Issue by sje30** [shower/shower#269]
Hi,

first, thanks for your work - this is a great tool.  I'm using rmdshower to make some slides via R and have noticed an issue with bullets rendered in Chrome (but not e.g. Safari), see here:

  https://github.com/MangoTheCat/rmdshower/issues/24

Any thoughts on places to debug this?  Here's an example slide deck of mine where the problem occurs:  
http://sje30.github.io/talks/2016/uknode.html

Thanks, stephen

**Comment by pepelsbey** [comment]
It’s most probably caused by CSS you packed as `data:uri`. You can try to fix it by specifying UTF-8 encoding to your data:
```
<link href="data:text/css,charset=UTF-8,…">
```
Otherwise it defaults to `charset=US-ASCII` but CSS [contains list bullets as UTF-8 characters](https://github.com/shower/ribbon/blob/master/styles/slide/content/lists.scss#L37).

I could probably fix it by specifying bullets as `\2022` instead of `•`, but could you please test `charset` fix first?

**Comment by sje30** [comment]
Thank you.  However, I don't think it worked for me to add the charset=UTF-8 line.  In my html example, I had several (5?) examples of data:text/css  so in each case I added the "charset=UTF-8" element but still the bullets do not render.

Maybe the author of rmdshower, @gaborcsardi has ideas too?

**Comment by sje30** [comment]
p.s. if it is possible for us to change bullet specification locally within rmdshower, that would also help test this.

**Comment by pepelsbey** [comment]
I could also recommend to set `self_contained: false` in your front matter so your files won’t be packed (I guess, haven’t tried it myself). As a temporary solution. I’m not sure how exactly you could test ASCII-compatible bulltes in your case since CSS is autocompressed.

Before I’ll make Shower’s themes ASCII-compatible (I wouldn’t want to do it since it makes code less readable), I’d make sure that it would help and it’s not a rmdshower’s bug, so it make sense to file an issue to rmdshower regarding UTF-8 strings packing. It’s definitely not a Shower’s fault since CSS is totally valid.

**Comment by gaborcsardi** [comment]
This is definitely R's fault I think, and it is probably an encoding issue. The other possible culprit is pandoc, that is creating the self-contained file. 

So yes, `self_contained: false` is a good start. Then (probably) nothing touches the CSS file, and everything should be fine.

Another possible workaround is to add custom CSS, and redefine the style with an escape sequence:
```
ul > li::before {
	content:'&#2022;';
	}
```

If this works, I can also add it to the `rmdshower` styles, these override the standard `shower` styles.

**Comment by sje30** [comment]
Thanks both!  I can confirm that setting `self_contained: false` works -- bullets render fine on Chrome.

Adding the `ul > li::before` snippet though had no effect when I tried it (copying the segment verbatim).

**Comment by sje30** [comment]
I think I finally got there:  this works for me:

```
.slide ul>li::before{padding-right:.5em;content:"\2022";}
```

so that bullets appear in chrome and safari now when standalone.
