### ISSUE TITLE
Supporting any other node for class="shower list" except body

### ISSUE THREAD

**Issue by viT-1** [shower/shower#287]
Do not turn on full screen mode by clicking on slide if this class marked on another node except body.

`<body><main class="shower list"><section class="slide">some slide</section></main><script src="js/shower.min.js"></body>`

**Comment by pepelsbey** [comment]
I though it’s been fixed already. Let me do some testing and digging in issues.

**Comment by pepelsbey** [comment]
OK, there are too many cases where `document.body` is used instead of just `.shower`. And this is not just a matter of search-and-replace, unfortunately. Shower depends on window size for scaling, meaning that it’s better to rely on the most outer container.

I think this could be fixed, though. But I’d make sure that functional tests are up and running, before even trying to touch this issue.

**Comment by shvaikalesh** [comment]
Latest `@shower/core` respects `containerSelector` option and does not reference `document.body` directly. However, we still use `window.onresize` handler for scaling: putting invisible `<iframe>` inside Shower container is too invasive, `ResizeObserver` is a bit unstable and requires reasonably large shim.
