### ISSUE TITLE
Documentation could do with expanding...

### ISSUE THREAD

**Issue by patrickhlauke** [shower/shower#301]
...to cover things like disabling hotkeys etc (via data attributes?) when using the ready-made template

**Comment by pepelsbey** [comment]
There’s a big shower-code rewrite happening at the moment, which will lead to some API changes and docs expanding. I‘ll make sure that this question is covered once we have 3.0 released.

**Comment by patrickhlauke** [comment]
Happy to help with documentation when you get to a stable-ish state. Just ping me.

**Comment by shvaikalesh** [comment]
@patrickhlaukeI assume you are having troubles with interactive elements. Latest `@shower/core` has improved approach of [detecting interactive elements](https://github.com/shower/core/blob/95134bc849ff67d9567b2cfaf1df1bc250787c36/lib/utils/index.js#L2) instead of tag names whitelist. Also, Shower will ignore [canceled events](https://dom.spec.whatwg.org/#canceled-flag).

We are very hesitant to introduce a flag for disabling hotkeys not only because we generally want to keep Shower simple, but
