### ISSUE TITLE
Integration with Tiddlywiki

### ISSUE THREAD

**Issue by kookma** [shower/shower#314]
Tiddlywiki.com is a simple and yet very powerful single file wiki engine. Shower is lightweight and very powerful presenter in html5 but creating and maintaining slides and presentation with it needs html5 knowledge and not easy to go with alot og tags and elements in an html editor.

Integration of these two will result in a powerful and easy to learn engine for presentation.

**Comment by pepelsbey** [comment]
Thank you for the idea. There are two concerns though:

1. It’s got to be a PR to have any perspective.
2. Every intergration should be not just written once, but constantly maintained.

If you’re somehow affiliated with Tiddlywiki there might be a interest to create and maintain such integration. Otherwise I don’t see how this idea might succeed.

**Comment by kookma** [comment]
Hi pepelsbey,
 Well, the TW has a large community of developer and we have volunteer to do that! I will also help.
Having HTML5 presentation which can be used in any platform on top of a wiki.
TW is open source and free and has a very easy and short learning curve. It already have support for KaTex, highlight.js, markdown and ....
I am sure this integration will result in a great and powerful tool.

Cheers

**Comment by pepelsbey** [comment]
Closing for now. Feel free to reopen if you’re willing to proceed.
