### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by davidneedham** [shower/shower#321]
When I clone the repo I get a message about vulnerabilities from GitHub. And when I run `npm install` I see `60 vulnerabilities found` and `Severity: 25 Low | 16 Moderate | 19 High`. 

I realize we may be waiting for the dependencies themselves to fix the issues, but is there a plan for Shower? Is there anything we should do in the meantime to mitigate the issues?

**Comment by pepelsbey** [comment]
AFAIK, even with those 19 High vulnerabilities you’re more than safe because the we only use those modules during build process and not anywhere on a server. It means there’s no possible way for such modules to affect your presenation or local computer.

Unfortunately npm does this audit no matter how you actually use your code and it probably makes sense, but it obviously raises the question you’ve just asked: is it safe? Yes, it’s.

Going from one dependency to another and hard-fixing versions or replacing convenient packages with patches only to get 100% audit score doesn’t make sense to me for such local-build-only project like Shower. But I’m more than open for ideas how to fix it any other way.

@shvaikalesh what do you think?

**Comment by avdeev** [comment]
Fixes would make sense if the dependency was used in runtime.
The shower is safe even with all these vulnerabilities.

**Comment by pepelsbey** [comment]
Closing it for now, meaning that currently there’s no reasonable action to be taken. Feel free to continue discussion though.
