### ISSUE TITLE
Hidden slides

### ISSUE THREAD

**Issue by DylanVanAssche** [shower/shower#351]
I was wondering if there's builtin support for hidden slides.
In PowerPoint/LibreOffice Impress you can hide slides from your presentation.
In edit mode, they are still visible but not when you present your presentation.

Does Shower have already support for this feature?
I couldn't find any issue or PR related to this, that's why I'm opening this issue.

**Comment by pepelsbey** [comment]
Sounds like a great idea to me! How about:

```
<section class="slide" hidden>
```

This’ll just work out the box, but in list mode theme will override hidden’s `display: none` with `block`.

**Comment by pepelsbey** [comment]
This might be a pretty quick feature to implement. But if you need something else, like a shortcut for hiding and showing such slides, this might take longer.

**Comment by DylanVanAssche** [comment]
I like the `hidden` approach with an override in list mode. It would be handy to show with a symbol or something else that the slide is hidden when presenting.

If you click on the slide in list mode, the slide must be viewable, but not in presentation mode.

**Comment by pepelsbey** [comment]
Marking hidden slide is not a big deal, but showing it in the presentation mode would require Shower plugin written in JS, not just a theme update. And this makes it a little more complicated since Shower 3.0 with shiny new plugin system is not released yet.

But let’s draft such plugin right in this issue. Please tell what exactly you think should happen when hidden slide is clicked in the list mode. And what should happen if I go forward and backward.

**Comment by DylanVanAssche** [comment]
If you click the slide in list mode, I should suggest that you can view it.
Navigation after clicking on a hidden slide, might be difficult.
Do we keep the hidden slide temporally enabled (during the current slide show) or not?
